steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cvtool-cli-api/admin-api:latest', '.']
  dir: '/'
  waitFor: ['-']

images:
- 'gcr.io/$PROJECT_ID/cvtool-cli-api/auth-api:latest'
