steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cvtool/cli-api:$TAG_NAME', '-t', 'gcr.io/$PROJECT_ID/cvtool/cli-api:latest', '.']
  dir: ''
  waitFor: ['-']

images:
- 'gcr.io/$PROJECT_ID/cvtool/cli-api:latest'
- 'gcr.io/$PROJECT_ID/cvtool/cli-api:$TAG_NAME'
