# coding: utf-8

from __future__ import absolute_import
from api.representations.annotations import Annotations
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ImageResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, version=None, job_id=None, original_uri=None, annotations=None, exif_annotations=None):
        """
        ImageResponse - a model defined in Swagger

        :param id: The id of this ImageResponse.
        :type id: str
        :param version: The version of this ImageResponse.
        :type version: str
        :param job_id: The job_id of this ImageResponse.
        :type job_id: str
        :param original_uri: The original_uri of this ImageResponse.
        :type original_uri: str
        :param annotations: The annotations of this ImageResponse.
        :type annotations: Annotations
        :param exif_annotations: The exif_annotations of this ImageResponse.
        :type exif_annotations: Annotations
        """
        self.swagger_types = {
            'id': str,
            'version': str,
            'job_id': str,
            'original_uri': str,
            'annotations': Annotations,
            'exif_annotations': Annotations
        }

        self.attribute_map = {
            'id': 'id',
            'version': 'version',
            'job_id': 'job_id',
            'original_uri': 'original_uri',
            'annotations': 'annotations',
            'exif_annotations': 'exif_annotations'
        }

        self._id = id
        self._version = version
        self._job_id = job_id
        self._original_uri = original_uri
        self._annotations = annotations
        self._exif_annotations = exif_annotations

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageResponse of this ImageResponse.
        :rtype: ImageResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self):
        """
        Gets the id of this ImageResponse.
        Image id.

        :return: The id of this ImageResponse.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ImageResponse.
        Image id.

        :param id: The id of this ImageResponse.
        :type id: str
        """

        self._id = id

    @property
    def version(self):
        """
        Gets the version of this ImageResponse.
        Image version id.

        :return: The version of this ImageResponse.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this ImageResponse.
        Image version id.

        :param version: The version of this ImageResponse.
        :type version: str
        """

        self._version = version

    @property
    def job_id(self):
        """
        Gets the job_id of this ImageResponse.
        Job id.

        :return: The job_id of this ImageResponse.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id):
        """
        Sets the job_id of this ImageResponse.
        Job id.

        :param job_id: The job_id of this ImageResponse.
        :type job_id: str
        """

        self._job_id = job_id

    @property
    def original_uri(self):
        """
        Gets the original_uri of this ImageResponse.
        The image to add to the database.

        :return: The original_uri of this ImageResponse.
        :rtype: str
        """
        return self._original_uri

    @original_uri.setter
    def original_uri(self, original_uri):
        """
        Sets the original_uri of this ImageResponse.
        The image to add to the database.

        :param original_uri: The original_uri of this ImageResponse.
        :type original_uri: str
        """

        self._original_uri = original_uri

    @property
    def annotations(self):
        """
        Gets the annotations of this ImageResponse.

        :return: The annotations of this ImageResponse.
        :rtype: Annotations
        """
        return self._annotations

    @annotations.setter
    def annotations(self, annotations):
        """
        Sets the annotations of this ImageResponse.

        :param annotations: The annotations of this ImageResponse.
        :type annotations: Annotations
        """

        self._annotations = annotations

    @property
    def exif_annotations(self):
        """
        Gets the exif_annotations of this ImageResponse.

        :return: The exif_annotations of this ImageResponse.
        :rtype: Annotations
        """
        return self._exif_annotations

    @exif_annotations.setter
    def exif_annotations(self, exif_annotations):
        """
        Sets the exif_annotations of this ImageResponse.

        :param exif_annotations: The exif_annotations of this ImageResponse.
        :type exif_annotations: Annotations
        """

        self._exif_annotations = exif_annotations

