# coding: utf-8

from __future__ import absolute_import
from api.representations.image_response import ImageResponse
from api.representations.meta_list_response import MetaListResponse
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class ImageListResponse(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, meta=None, items=None):
        """
        ImageListResponse - a model defined in Swagger

        :param meta: The meta of this ImageListResponse.
        :type meta: MetaListResponse
        :param items: The items of this ImageListResponse.
        :type items: List[ImageResponse]
        """
        self.swagger_types = {
            'meta': MetaListResponse,
            'items': List[ImageResponse]
        }

        self.attribute_map = {
            'meta': 'meta',
            'items': 'items'
        }

        self._meta = meta
        self._items = items

    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ImageListResponse of this ImageListResponse.
        :rtype: ImageListResponse
        """
        return deserialize_model(dikt, cls)

    @property
    def meta(self):
        """
        Gets the meta of this ImageListResponse.

        :return: The meta of this ImageListResponse.
        :rtype: MetaListResponse
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """
        Sets the meta of this ImageListResponse.

        :param meta: The meta of this ImageListResponse.
        :type meta: MetaListResponse
        """

        self._meta = meta

    @property
    def items(self):
        """
        Gets the items of this ImageListResponse.

        :return: The items of this ImageListResponse.
        :rtype: List[ImageResponse]
        """
        return self._items

    @items.setter
    def items(self, items):
        """
        Sets the items of this ImageListResponse.

        :param items: The items of this ImageListResponse.
        :type items: List[ImageResponse]
        """

        self._items = items

