apiVersion: v1
kind: Service
metadata:
  name: swagger-server-api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"  
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
  selector:
    app: swagger-server-api
  type: {{ .Values.swaggerServerApi.serviceType }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-swagger-server
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.swaggerServerApi.replicaCount }}
  template:
    metadata:
      labels:
        app: swagger-server-api
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-p", "8081",
          "-a", "127.0.0.1:8080",
          "-s", "{{ .Values.swaggerServerApi.cloudEndpoints.service }}.endpoints.{{ .Values.projectId }}.cloud.goog",
          "-v", "{{ .Values.swaggerServerApi.cloudEndpoints.version }}",
        ]
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /var/lib/nginx/extra
          name: config        
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10        
      - name: swagger-server-api
        image: {{ .Values.imageRegistry }}/{{ .Values.swaggerServerApi.image.name }}:{{ .Values.swaggerServerApi.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      volumes:
        - name: config
          configMap:
            name: nginx-extra-config
            items:
            - key: readiness-probe-conf
              path: readiness-probe.conf            



