# coding: utf-8

from __future__ import absolute_import

from api.util import deserialize_model
from .base_model_ import Model


class JobInputParameters(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        JobInputParameters - a model defined in Swagger

        """
        self.swagger_types = {
            
        }

        self.attribute_map = {
            
        }


    @classmethod
    def from_dict(cls, dikt):
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobInputParameters of this JobInputParameters.
        :rtype: JobInputParameters
        """
        return deserialize_model(dikt, cls)
