# coding: utf-8

from __future__ import absolute_import
from api.models.settings import Settings
import re
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Tenant(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, description: str=None, settings: Settings=None):
        """
        Tenant - a model defined in Swagger

        :param id: The id of this Tenant.
        :type id: str
        :param name: The name of this Tenant.
        :type name: str
        :param description: The description of this Tenant.
        :type description: str
        :param settings: The settings of this Tenant.
        :type settings: Settings
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'description': str,
            'settings': Settings
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'settings': 'settings'
        }

        self._id = id
        self._name = name
        self._description = description
        self._settings = settings

    @classmethod
    def from_dict(cls, dikt) -> 'Tenant':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tenant of this Tenant.
        :rtype: Tenant
        """
        return deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """
        Gets the id of this Tenant.

        :return: The id of this Tenant.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """
        Sets the id of this Tenant.

        :param id: The id of this Tenant.
        :type id: str
        """
        if id is not None and len(id) > 64:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `64`")
        if id is not None and len(id) < 3:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `3`")
        if id is not None and not re.search('[a-z0-9-_\\.]{3,64}', id):
            raise ValueError("Invalid value for `id`, must be a follow pattern or equal to `/[a-z0-9-_\\.]{3,64}/`")

        self._id = id

    @property
    def name(self) -> str:
        """
        Gets the name of this Tenant.

        :return: The name of this Tenant.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """
        Sets the name of this Tenant.

        :param name: The name of this Tenant.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """
        Gets the description of this Tenant.

        :return: The description of this Tenant.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """
        Sets the description of this Tenant.

        :param description: The description of this Tenant.
        :type description: str
        """

        self._description = description

    @property
    def settings(self) -> Settings:
        """
        Gets the settings of this Tenant.

        :return: The settings of this Tenant.
        :rtype: Settings
        """
        return self._settings

    @settings.setter
    def settings(self, settings: Settings):
        """
        Sets the settings of this Tenant.

        :param settings: The settings of this Tenant.
        :type settings: Settings
        """

        self._settings = settings

