# coding: utf-8

from __future__ import absolute_import
from models.project import Project
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Projects(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, items: List[Project]=None):
        """
        Projects - a model defined in Swagger

        :param items: The items of this Projects.
        :type items: List[Project]
        """
        self.swagger_types = {
            'items': List[Project]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'Projects':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Projects of this Projects.
        :rtype: Projects
        """
        return deserialize_model(dikt, cls)

    @property
    def items(self) -> List[Project]:
        """
        Gets the items of this Projects.

        :return: The items of this Projects.
        :rtype: List[Project]
        """
        return self._items

    @items.setter
    def items(self, items: List[Project]):
        """
        Sets the items of this Projects.

        :param items: The items of this Projects.
        :type items: List[Project]
        """

        self._items = items

