# coding: utf-8

from __future__ import absolute_import
from models.tenant import Tenant
from .base_model_ import Model
from datetime import date, datetime
from typing import List, Dict
from ..util import deserialize_model


class Tenants(Model):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, items: List[Tenant]=None):
        """
        Tenants - a model defined in Swagger

        :param items: The items of this Tenants.
        :type items: List[Tenant]
        """
        self.swagger_types = {
            'items': List[Tenant]
        }

        self.attribute_map = {
            'items': 'items'
        }

        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'Tenants':
        """
        Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tenants of this Tenants.
        :rtype: Tenants
        """
        return deserialize_model(dikt, cls)

    @property
    def items(self) -> List[Tenant]:
        """
        Gets the items of this Tenants.

        :return: The items of this Tenants.
        :rtype: List[Tenant]
        """
        return self._items

    @items.setter
    def items(self, items: List[Tenant]):
        """
        Sets the items of this Tenants.

        :param items: The items of this Tenants.
        :type items: List[Tenant]
        """

        self._items = items

